### ISSUE TITLE
Cannot deploy to heroku

### ISSUE THREAD

**Issue by mrtysn** [agungsb/create-react-app-ssr-pwa#4]
Hi, I can't get this project running on heroku. I wasn't able to arrange dependencies, devDependencies and automated builds. Knowing the interior of the project better, can you help me come up with a solution?

Here is what I did for deployment in previous a Next.js project:

> "scripts": {
    "dev": "node server.js",
    "start": "NODE_ENV=production node server.js",
    "build": "next build",
    "heroku-postbuild": "npm run build"
  }

Below is what I appended to scripts, but didn't work out:

```
"heroku-prebuild": "export NPM_CONFIG_PRODUCTION=false; export NODE_ENV=; NPM_CONFIG_PRODUCTION=false NODE_ENV=development npm install --only=dev --dev",
"heroku-postbuild": "export NPM_CONFIG_PRODUCTION=true; export NODE_ENV=production; npm run build"
```

Heroku is not a must by the way. Any kind of deployment is OK for me, as long as I can set-up a high performance, low initial-load-time environment. Currently, I am comparing the alternatives which provide SSR and yours looks like the best starting option out there.

**Comment by agungsb** [comment]
Hi @mrtysn , thanks for your support. 

I'm not familiar with Heroku, but I tried my best. I've successfully deployed the boilerplate to Heroku with minimum configuration. Here's the update of `scripts` inside `package.json`:

```
"scripts": {
    "start": "node scripts/start.js",
    "build": "node scripts/build.js",
    "test": "node scripts/test.js --env=jsdom",
    "dev": "NODE_ENV=development node server/index.js",
    "prod": "NODE_ENV=production node server/index.js",
    "win-dev": "set NODE_ENV=development&&node server/index.js",
    "win-prod": "set NODE_ENV=production&&node server/index.js",
    "heroku-prebuild": "NPM_CONFIG_PRODUCTION=false NODE_ENV=development npm install --only=dev --dev",
    "heroku-postbuild": "NPM_CONFIG_PRODUCTION=true NODE_ENV=production"
  }
```

Heroku will deploy the application by using `npm start`. Here is the [link of the deployed app.](https://create-react-app-ssr-pwa.herokuapp.com/)
